### ISSUE TITLE
circVBufArrayInterface size() expects one argument only

### ISSUE THREAD

**Issue by kashefy** [TWOEARS/auditory-front-end#22]
`circVBufArrayInterface` has its own implementation for size()
It only expects a single argument. However, the Signal class uses it while assuming it accepts a second dimension argument [Example: size(sObj.Data,1)](https://github.com/TWOEARS/auditory-front-end/blob/master/src/Signals/Signal.m#L304)

This call produces the following error:
Error using circVBufArrayInterface/size
Too many input arguments.

Will provide a PR with a possible solution shortly.

**Comment by hagenw** [comment]
Fixed by #23
